### ISSUE TITLE
Error instantiating Ppc_Melt_Polynomial

### ISSUE THREAD

**Issue by lmahoney9** [OlympusMonds/lithospheric_modelling_recipe#11]
Hi Luke,

On Friday all of my model runs on Magnus started throwing an error related to instantiating Ppc_Melt_Polynomial.

I've tried repeating some successful models from earlier in the week and they now return the same error, which looks something like this:

...
        Instantiating MaterialPointsSwarm as borderGaussMaterialSwarm
	Instantiating Ppc_LinearDensity as densTemp_sediment
2: Cannot find default constructor function for type 'Ppc_Melt_Polynomial'
8: Cannot find default constructor function for type 'Ppc_Melt_Polynomial'
2: Could you have meant one of these?
4: 	Ppc_Polynomial (73.68% similar)
2: 	Ppc_Polynomial (73.68% similar)
6: 	Ppc_Polynomial (73.68% similar)
2: 	MultiRheologyMaterial (47.62% similar)
4: 	MultiRheologyMaterial (47.62% similar)
2: 	Ppc_IsMaterial (47.37% similar)
...

Any ideas on the origin of this error?

Thanks mate.

Luke

**Comment by RhiGarett** [comment]
I have exactly the same problem and have also tried running models that have previously worked, but with no success.

**Comment by OlympusMonds** [comment]
Sorry, I was trying to compile the new version of UW, and ran into some issues.

You should be able to switch your lmrStart.xml Underworld_Binary to point to:
/group/q97/software/EarthByte_Underworld_2/build/bin/Underworld.

I'll post in here when the new version is fixed.

**Comment by lmahoney9** [comment]
No worries Luke - thanks for compiling new version for us!

I've changed lmrStart.xml Underworld_Binary but still getting the same error sadly.

I'm happy to wait until you can stitch together the new version.

**Comment by linuxjackto3** [comment]
thanks www.movied.org

**Comment by OlympusMonds** [comment]
OK, hopefully should be fixed now. Go back to using the normal path to Underworld.

I've also created a wiki entry: https://github.com/OlympusMonds/lithospheric_modelling_recipe/wiki/Compiling-EarthByte_Underworld-on-Magnus
to explain how UW is compiled on Magnus, so if I die someone else can do it.

**Comment by OlympusMonds** [comment]
OK, I have tested UW on magnus (both thermal equil and thermo-mechanical) and it works OK for me.

Just a useful tip:
If you need to test something, and the queue is too long, you can run a debug job. Debug jobs have a max-time of ~1 hour, and only one node, but they start straight away.

To use it, just add:
#SBATCH --partition=debugq

to your submitjob.sh file (underneath all the other #SBATCH commands).

**Comment by lmahoney9** [comment]
Awesome - thanks heaps Luke.

p.s. please don't die!!
