### ISSUE TITLE
Can you help me setup the multigrid in UW?

### ISSUE THREAD

**Issue by QwZhang** [OlympusMonds/lithospheric_modelling_recipe#12]
Hi,
I am a beginner for Underworld (v1.7.1). I find it's computationally expensive to run UW, for instance, when I try to rerun a 2D subduction model after extending it into a 3D one (I tried 125x70x18 elements to get required resolution of 20x10x40 km for subduction with 20 particles per element), it became extremely slow (I used 100 CPU cores and it spent almost two days to finish 100 steps). I have been followed the configuration involving using of the **Stokes_SLE_UzawaSolver** as demonstrated in **InputFiles-1.7.0\InputFiles\SlabSubduction.xml**:

```
      <struct name="uzawa" mergeType="replace">
         <param name="Type">Stokes_SLE_UzawaSolver</param>
         <param name="Preconditioner">preconditioner</param>
         <param name="tolerance">1.0e-5</param>
         <param name="maxIterations">5000</param>
         <!-- must be in slab models as DaveStegman has tuned this simulation.
         but this is dangerous and we must calculate a better param selection
         for uzawa to reasonably converge 
         JulianGiordani 24Jul07
         -->
         <param name="useAbsoluteTolerance">true</param>
      </struct>
```

Here is what the **FrequentOutput.dat** recorded for this particular run:

```
#       Timestep            Time            Vrms        CPU_Time
               0               0     4.01962e-10         6789.97
               1     1.70796e+12     4.37561e-10         8856.23
               2     3.23728e+12     4.66809e-10         10874.4
               3     4.70818e+12     4.90486e-10         12451.9
               4     6.10714e+12     5.14847e-10         13966.6
               5     7.47714e+12     5.45636e-10         16178.5
              ...
              98      8.1864e+13     2.53321e-09          158105
              99     8.23665e+13     2.55131e-09          158905
             100     8.28681e+13     2.56969e-09          159887
```

It seems that the wall time is too much for this 3D model even taking into consideration of increase of computation after transferring a 2D model to 3D one. 
So I want to try multigrid to get fast convergence rate. This is crucial if I want to run similar model at current or even higher resolution with more CPU cores. 
In doing so, I get very limited information in the user manual (v.1.5.2 and v.1.7.1) about how to setup Underworld with multigrid:

```
<include>StgFEM/MultigridForRegular.xml</include>
<param name="mgLevels">3</param> <!-- The number of MG levels. -->
```

And I am still confused about:
1. How can I setup Underworld with multigrid capability? Does it to necessary to remove all the configuration about the Uzawa solver listed above if one wish to activate multigrid-related solver by including the **StgFEM/MultigridForRegular.xml** and set a appropriate multigrid levels (**mgLevels**)?
2. How can I control the max number (if needed) of iterations and tolerance for the multigrid solver?
3. According to the user manual (v.1.7.1) and how prof. Moresi describes about the usage of multigrid in Underworld in his [Moresi2007](http://www.nature.com/nature/journal/v508/n7495/full/nature13033.html#supplementary-information) nature paper, which is about 3D subduction:

> In a model domain we use a resolution of 256x96x96 elements with a uniform grid spacing in each coordinate direction. This gives a grid resolution of 8.3 km in the vertical direction, and a horizontal resolution of 30 km. We initially seed this grid with 15 material points randomly located in each element onto which the distribution of distinct materials from the original configuration of distinct material domains is mapped when each run is initialized. We verified the model outputs using a lower resolution grid of 192x64x64. **Note that the number of elements is constrained by our use of a simple geometrical-multigrid solver which dictates the resolution in each coordinate direction to be N 5 m32n elements, where m is a small integer (typically 2, 3, 5) and n is the number of levels in the multigrid mesh hierarchy.**

It seems that the multigrid levels and number of elements in certain direction (e.g., x direction) cannot be arbitrary. For example, if multigrid level = 3, the number of elements in x, y, z direction should at least be able to be divided exactly by 2 for 3 times?

Any help or hints will be appreciated!

Best,
Qw

**Comment by OlympusMonds** [comment]
Hello,

The Lithospheric Modelling Recipe uses these flags by default for 3D models:
```
--mgLevels={mg_levels} -mg_coarse_pc_factor_mat_solver_package mumps -mg_coarse_pc_type lu -mg_coarse_ksp_type preonly -A11_pc_mg_smoothup 2 -A11_pc_mg_smoothdown 2 -A11_ksp_monitor -options_left -log_summary
```
where {mg_levels} is the number of multigrid levels you want to use. Essentially it is using multigrid, with a direct solve on the coarsest level. Just a note, if you choose too many levels, it can make the direct solve not worth the time. Too few levels and either it takes too long to setup, or the memory usage is very large. 
NOTE: Your PETSc installation must have MUMPs installed for this to work.

In regard to the multigrid level - yes, you do need to choose a resolution that can be halved and remain an integer by the number of levels times. The example you provided was correct.

Regarding the tolerances - the multigrid stuff uses the same lineartolerance and nonlineartolerance variables. You can set them in the uzawa struct, or via the command line:
```
--linearTolerance=1e-5 --linearMinIterations=10 --linearMaxIterations=5000
--nonLinearTolerance=1e-3 --nonLinearMinIterations=2 --nonLinearMaxIterations=5000
```

To actually activate multigrid, the LMR just includes this file: `{uw_root}/StgFEM/Apps/src/MultigridForRegular.xml`, where {uw_root} is the root directory of your Underworld installation.

So a full run might look something like:
```
mpirun -np 100 $UW_ROOT/build/bin/Underworld $UW_ROOT/Underworld/InputFiles-1.7.0\InputFiles\SlabSubduction.xml $UW_ROOT/StgFEM/Apps/src/MultigridForRegular.xml --mgLevels=4 -mg_coarse_pc_factor_mat_solver_package mumps -mg_coarse_pc_type lu -mg_coarse_ksp_type preonly -A11_pc_mg_smoothup 2 -A11_pc_mg_smoothdown 2 -A11_ksp_monitor -options_left -log_summary --linearTolerance=1e-5 --linearMinIterations=10 --linearMaxIterations=5000 --nonLinearTolerance=1e-3 --nonLinearMinIterations=2 --nonLinearMaxIterations=5000
```

You may want to consider moving to using Underworld2, which uses Python as a way to control the model. You can see a slab example here: https://github.com/underworldcode/underworld2/blob/master/docs/examples/1_07_SlabSubduction.ipynb
It is in active development, and supports multigrid, parallelisation, and a bunch of other things. It also exposes a lot of the maths to the user, which is good for scientific communication within your workflow.

Alternately, if you still want to use Underworld1.8, you could try running the LMR. You need a custom version of Underworld, which you can find here: https://github.com/OlympusMonds/EarthByte_Underworld
Instructions for installing it are here:
https://github.com/OlympusMonds/lithospheric_modelling_recipe/wiki/Installing-Underworld-for-the-LMR

**Comment by QwZhang** [comment]
Hi, @OlympusMonds,
Many thanks for your reply, which is very helpful for me. When I try new run with additional multigrid configrations detailed by you, the machine stoped and output error massages like:
```
PETScMGSolver_UpdateMats-WorkVecs 0.118387
[0]PETSC ERROR: --------------------- Error Message ------------------------------------
[0]PETSC ERROR: No support for this operation for this object type!
[0]PETSC ERROR: **Matrix format mpiaij does not have a solver package mumps for LU. Perhaps you must ./configure with --download-mumps!**
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Petsc Release Version 3.2.0, Patch 7, Thu Mar 15 09:30:51 CDT 2012 
[0]PETSC ERROR: See docs/changes/index.html for recent updates.
[0]PETSC ERROR: See docs/faq.html for hints about trouble shooting.
[0]PETSC ERROR: See docs/index.html for manual pages.
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: /WORK/app/UnderWorld/1.7.0/build/bin/Underworld on a arch-linu named cn9721 by ac_gig_gf_1 Mon Apr  4 13:26:46 2016
[0]PETSC ERROR: Libraries linked from /WORK/app/petsc/3.2-p7/lib
[0]PETSC ERROR: Configure run at Tue Mar 10 12:07:11 2015
[0]PETSC ERROR: Configure options --prefix=/WORK/app/petsc/3.2-p7 --download-hypre=/HOME/nscc_ts_1/petsc/hypre-2.9.1a.tar.gz --with-debugging=no --with-pic=1 --with-shared-libraries=1 --with-cc=mpicc --with-cxx=mpicxx --with-fc=mpif90 --download-f-blas-lapack=/HOME/nscc_ts_1/petsc/fblaslapack-3.4.2.tar.gz CFLAGS="-fPIC -fopenmp" CXXFLAGS="-fPIC -fopenmp" FFLAGS="-fPIC -fopenmp" FCFLAGS="-fPIC -fopenmp" F90FLAGS="-fPIC -fopenmp" F77FLAGS="-fPIC -fopenmp" PETSC_DIR=/HOME/nscc_ts_1/petsc/petsc-3.2-p7
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: MatGetFactor() line 3948 in /HOME/nscc_ts_1/petsc/petsc-3.2-p7/src/mat/interface/matrix.c
[0]PETSC ERROR: PCSetUp_LU() line 133 in /HOME/nscc_ts_1/petsc/petsc-3.2-p7/src/ksp/pc/impls/factor/lu/lu.c
[0]PETSC ERROR: PCSetUp() line 819 in /HOME/nscc_ts_1/petsc/petsc-3.2-p7/src/ksp/pc/interface/precon.c
[0]PETSC ERROR: KSPSetUp() line 260 in /HOME/nscc_ts_1/petsc/petsc-3.2-p7/src/ksp/ksp/interface/itfunc.c
[0]PETSC ERROR: PCSetUp_MG() line 678 in /HOME/nscc_ts_1/petsc/petsc-3.2-p7/src/ksp/pc/impls/mg/mg.c
[0]PETSC ERROR: PCSetUp() line 819 in /HOME/nscc_ts_1/petsc/petsc-3.2-p7/src/ksp/pc/interface/precon.c
[0]PETSC ERROR: KSPSetUp() line 260 in /HOME/nscc_ts_1/petsc/petsc-3.2-p7/src/ksp/ksp/interface/itfunc.c
[0]PETSC ERROR: KSPSolve() line 379 in /HOME/nscc_ts_1/petsc/petsc-3.2-p7/src/ksp/ksp/interface/itfunc.c
``` 
As you mentioned, my current PETSc installation lacks MUMPs. I will have to rebuild PETSc with MUMPs enabled.

Thank you for your time!
Best,
QW

**Comment by OlympusMonds** [comment]
I've found these installation parameters to work well for PETSc: https://github.com/OlympusMonds/lithospheric_modelling_recipe/wiki/Installing-Underworld-for-the-LMR#installing-petsc

**Comment by QwZhang** [comment]
All right. I have been running UW on Tianhe-2, so I will have to wait for the administrator to rebuild  PETSc. 
Qw
