### ISSUE TITLE
Defining a PolygonShape in appropriate axes and units

### ISSUE THREAD

**Issue by sb926** [OlympusMonds/lithospheric_modelling_recipe#4]
I'm experimenting with defining some PolygonShapes and am a little unclear on how to define their vertices from the instructions at http://underworldproject.org/codex-v1.6.0/StgDomain.htm

Given the Y axis in the lmr is depth but for the underworld project they set Z as depth, is it as simple as changing the definition below to give x and z coordinates, with the depth defined by the startY and endY? I also wasn't clear on whether to give kilometre values in the ascii list for vertice locations or whether it's a scaled value (seems odd that they are decimals in the example below)?

Example on 
 <list name="vertices"> 
<asciidata> 
<columnDefinition name = "x" type="double"/>
 <columnDefinition name = "y" type="double"/> 
0.3 0.2 
0.50 0.2 
0.3 0.50
 </asciidata>

**Comment by sb926** [comment]
It took out some of the code I'd copied from the example! But essentially the bit I was looking at is where the ascii input list of vertice points are fed to the structure for the material.

**Comment by OlympusMonds** [comment]
Hi Sarah!

You need to make sure each column has a unit defined OR use the default units in the numbers, which is metres.

For example, without defining explicit units (aka, just using metres):

```xml
    <struct name="lowercrustnotchShape"> 
        <param name="Type"> PolygonShape </param> 
        <param name="startZ"> minZ </param> 
        <param name="endZ"> maxZ </param> 
         
        <list name="vertices"> 
            <asciidata> 
            <columnDefinition name = "x" type="double"/> 
            <columnDefinition name = "y" type="double"/> 
            -10000  -40000 
                 0  -48000 
             10000  -40000 
            </asciidata> 
        </list>
    </struct>
```

or you can explicitly use kilometres:

```xml
    <struct name="lowercrustnotchShape"> 
        <param name="Type"> PolygonShape </param> 
        <param name="startZ"> minZ </param> 
        <param name="endZ"> maxZ </param> 
         
        <list name="vertices"> 
            <asciidata> 
            <columnDefinition name = "x" type="double" units="km"/> 
            <columnDefinition name = "y" type="double" units="km"/> 
            -10  -40 
                 0  -48 
             10  -40 
            </asciidata> 
        </list>
    </struct>
```
