### ISSUE TITLE
Troubleshooting missing Lower Crust marker beds

### ISSUE THREAD

**Issue by lmahoney9** [OlympusMonds/lithospheric_modelling_recipe#5]
Hi Luke,

Upper crust and Mantle markers are now working fine but I'm still having trouble getting Lower Crust markers to work.  Have I made any obvious mistakes in lmrMaterials attached? I can email you the xml if required.

Cheers,
Luke

[lmrMaterials.txt](https://github.com/OlympusMonds/lithospheric_modelling_recipe/files/81889/lmrMaterials.txt)

**Comment by OlympusMonds** [comment]
Aha! Found the problem!

Here is an example of one of the lowercrust markers:
```xml
    <struct name="lowercrustMarker0">
        <param name="Type"> Box </param>
        <param name="startX" units="km"> 0 </param>
        <param name="endX" units="km"> 20 </param>
        <param name="startY"> -40 </param>
        <param name="endY"> -20 </param>
        <param name="startZ"> minZ </param>
        <param name="endZ"> maxZ </param>
    </struct>
```

Everything looks good - except!:
```xml
        <param name="startY"> -40 </param>
        <param name="endY"> -20 </param>
```
needs to be:
```xml
        <param name="startY" units="km"> -40 </param>
        <param name="endY" units="km"> -20 </param>
```
Without the units, all your marker beds were going from -20 metres depth to -40 metres depth!

**Comment by lmahoney9** [comment]
Argh! Thanks Luke
