### ISSUE TITLE
Surprising inversion of viscosity values in a single timestep

### ISSUE THREAD

**Issue by sb926** [OlympusMonds/lithospheric_modelling_recipe#7]
I am testing a simple model that is 600 km wide by 300 km deep and with an asthenospheric layer at base of model. I was surprised that for the first timestep after thermal equilibration the left and right ~100 kms of the lithosphere were already at the viscosity assigned to the asthenosphere. Then between timestep 10 and 11 those regions return to the expected lithospheric viscosity and the central part of the lithosphere swaps to asthenospheric viscosity.  I wondered whether these problems are due to the timesteps being too big? Or is it a problem with my defined properties of the litho/asthenosphere? For the asthenosphere I used the densTemp_asthenosphere defined in the rheology library, but made few other changes from the example setup.

**Comment by OlympusMonds** [comment]
Can you post some pics of what you mean? 
What are the boundary conditions?
What does the velocity field look like?

**Comment by sb926** [comment]
Looks like the problem was lack of units on the asthenosphere!
